# Generated by Django 3.1.7 on 2021-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_company_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_customer',
            name='cust_regi_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
