# Generated by Django 3.1.7 on 2021-06-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_company_customer_cust_regi_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nm', models.CharField(default='', max_length=200)),
                ('pro_pr', models.PositiveIntegerField(default=0)),
                ('pro_qty', models.PositiveIntegerField(default=0)),
                ('pro_img', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='ProductPic/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company_data')),
            ],
        ),
    ]
