# Generated by Django 3.2.3 on 2022-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_orders',
            name='status',
            field=models.CharField(default='False', max_length=200),
        ),
    ]
